app/public/wp-content/plugins/newtheme-blank-alvax/admin/class-new-admin.php
app/public/wp-content/plugins/newtheme-blank-alvax/admin/partials/new-admin-display-edit.php
app/public/wp-content/plugins/newtheme-blank-alvax/admin/partials/new-admin-display.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-activator.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-ajax.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-build-menupage.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-cargador.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-crud-json.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-deactivator.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-i18n.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-master.php
app/public/wp-content/plugins/newtheme-blank-alvax/includes/class-new-metaboxes.php
app/public/wp-content/plugins/newtheme-blank-alvax/public/class-new-public.php
